column_width = 120
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
line_endings = "Windows"
newline_end_of_file = true
skip = ["scripts/SensorList/images", "scripts/SensorList/i18n"]
